### ISSUE TITLE
Bug: region is not displayed in the correct place?

### ISSUE THREAD

**Issue by Potatochurchman** [xdkyree/LeagueChallenges#2]
I don't know if this is intentional, but the region is somewhat inconsistent about its position.
If we look at the screenshot: Aphelio's region is right after its name, but if it has at least one attribute set, (like "poke" for Zoe) then it will be displayed in the last possible column.
![image](https://user-images.githubusercontent.com/47665714/180214661-cfb2de2b-8823-4cc5-9542-f94263672a63.png)

**Comment by xdkyree** [comment]
Good catch! It's due to text centering and allignment. I just eye-balled in a way it looks good. If you have any suggestions how it may look better feel free to add another issue :)).

**Comment by Potatochurchman** [comment]
> Oh and also bear in mind that champions can have multiple regions, that's why it's hard to find a good way to display it.

Hmm good point. I don't have much time right now, but I'll think about it when I have more time again. I bet there is a good solution for this :)
